version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
